[package]
name = "password-generator"
version = "0.1.0"
authors = ["weizhang9 <wei.zhang@sky.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"